// <auto-generated />
using System;
using EduTrack360.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduTrack360.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929162856_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduTrack360.Models.PreparationDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OptionLabel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PreparationDomains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "University Study",
                            OptionLabel = "Department"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Job Preparation",
                            OptionLabel = "Career Track"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Bank Job Preparation",
                            OptionLabel = "Job Type"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "BCS Preparation",
                            OptionLabel = "Preparation Stage"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Language Learning",
                            OptionLabel = "Language"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Higher Studies Preparation",
                            OptionLabel = "Study Goal"
                        });
                });

            modelBuilder.Entity("EduTrack360.Models.PreparationOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemDefined")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PreparationDomainId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreparationDomainId");

                    b.ToTable("PreparationOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "CSE",
                            PreparationDomainId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "EEE",
                            PreparationDomainId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Civil Engineering",
                            PreparationDomainId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Pharmacy",
                            PreparationDomainId = 1
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "BBA",
                            PreparationDomainId = 1
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Microbiology",
                            PreparationDomainId = 1
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "C#/.NET Developer",
                            PreparationDomainId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Java Developer",
                            PreparationDomainId = 2
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Python Developer",
                            PreparationDomainId = 2
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "DevOps Engineer",
                            PreparationDomainId = 2
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Bank IT",
                            PreparationDomainId = 3
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Officer",
                            PreparationDomainId = 3
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Preliminary",
                            PreparationDomainId = 4
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Written",
                            PreparationDomainId = 4
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Viva",
                            PreparationDomainId = 4
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "English",
                            PreparationDomainId = 5
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Japanese",
                            PreparationDomainId = 5
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "German",
                            PreparationDomainId = 5
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "IELTS",
                            PreparationDomainId = 6
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "GRE",
                            PreparationDomainId = 6
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "Masters Admission",
                            PreparationDomainId = 6
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            IsSystemDefined = true,
                            Name = "PhD Admission",
                            PreparationDomainId = 6
                        });
                });

            modelBuilder.Entity("EduTrack360.Models.StudyTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ActualHours")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentTopicId")
                        .HasColumnType("int");

                    b.Property<double>("PlannedHours")
                        .HasColumnType("float");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudyWorkspaceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ParentTopicId");

                    b.HasIndex("StudyWorkspaceId");

                    b.ToTable("StudyTopics");
                });

            modelBuilder.Entity("EduTrack360.Models.StudyWorkspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomOptionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Goal")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PreparationDomainId")
                        .HasColumnType("int");

                    b.Property<int?>("PreparationOptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PreparationDomainId");

                    b.HasIndex("PreparationOptionId");

                    b.ToTable("StudyWorkspaces");
                });

            modelBuilder.Entity("EduTrack360.Models.PreparationOption", b =>
                {
                    b.HasOne("EduTrack360.Models.PreparationDomain", "PreparationDomain")
                        .WithMany("Options")
                        .HasForeignKey("PreparationDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PreparationDomain");
                });

            modelBuilder.Entity("EduTrack360.Models.StudyTopic", b =>
                {
                    b.HasOne("EduTrack360.Models.StudyTopic", "ParentTopic")
                        .WithMany("SubTopics")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EduTrack360.Models.StudyWorkspace", "StudyWorkspace")
                        .WithMany("Topics")
                        .HasForeignKey("StudyWorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentTopic");

                    b.Navigation("StudyWorkspace");
                });

            modelBuilder.Entity("EduTrack360.Models.StudyWorkspace", b =>
                {
                    b.HasOne("EduTrack360.Models.PreparationDomain", "PreparationDomain")
                        .WithMany("Workspaces")
                        .HasForeignKey("PreparationDomainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduTrack360.Models.PreparationOption", "PreparationOption")
                        .WithMany("Workspaces")
                        .HasForeignKey("PreparationOptionId");

                    b.Navigation("PreparationDomain");

                    b.Navigation("PreparationOption");
                });

            modelBuilder.Entity("EduTrack360.Models.PreparationDomain", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("EduTrack360.Models.PreparationOption", b =>
                {
                    b.Navigation("Workspaces");
                });

            modelBuilder.Entity("EduTrack360.Models.StudyTopic", b =>
                {
                    b.Navigation("SubTopics");
                });

            modelBuilder.Entity("EduTrack360.Models.StudyWorkspace", b =>
                {
                    b.Navigation("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
